### ISSUE TITLE
Add a feature that enables one to set the desired password length

### ISSUE THREAD

**Issue by joshuaombasa** [joshuaombasa/RANDOM-PASSWORD-GENERATOR#1]
Currently the app generates a 15 character password. We need to add flexibility so that the user can specify their desired password length.

**Comment by SamEarth79** [comment]
Hi, I can solve this by adding a field to fetch desired length which will then be used to generate the password. Can you assign this to me?

**Comment by joshuaombasa** [comment]
@SamEarth79 Feel free to contribute. I've assigned you both issues.

**Comment by SamEarth79** [comment]
Hi, I have created a pull request
#4
